### ISSUE TITLE
Questions about mol dataset transforming

### ISSUE THREAD

**Issue by Frankie123421** [harryjo97/GDSS#4]
Hi, nice work and thanks for sharing the codes. I have some questions on the transforming of molecular datasets. Specifically, in `utils/data_loader_mol.py` line 40 _function_ `get_transform_fn`, you create `x_` with the last place for virtual nodes. However, this place is then removed by the following `x = x[:, :-1]`, which makes me a little bit confused. Another question is that you do not consider aromatic bond as excluded by `adj[:3]`. Although I notice that _moflow_ also did so, I wonder why and further in the generation process how to form aromatic bonds. Thanks in advance.

**Comment by SeulLee05** [comment]
Hi, thanks for your interest in our work.
`utils/data_loader_mol.py` is based on the code of MoFlow and GraphEBM and we made minor modifications to the code, and we’re sorry if there’s some confusion because of this.
First of all, we don’t utilize virtual nodes unlike GraphEBM, so we don’t need the last element of `x`. You can actually just remove the virtual node part altogether.
Also, the last element of `adj` is not for aromatic bonds, but for virtual edges as explained in GraphEBM. In MoFlow, GraphEBM, and our work, all molecules are kekulized, so there are no aromatic bonds. And we do not utilize virtual edges.
Hope this clarifies your questions.

**Comment by SeulLee05** [comment]
Hi, thanks for your interest in our work.
`utils/data_loader_mol.py` is based on the code of GraphEBM and we made minor modifications to the code, and we’re sorry if there’s some confusion because of this.
First of all, we don’t utilize virtual nodes unlike GraphEBM, so we don’t need the last element of `x`. You can actually just remove the virtual node part altogether.
Also, the last element of `adj` is not for aromatic bonds, but for virtual edges as explained in GraphEBM. In GraphEBM and our work, all molecules are kekulized, so there are no aromatic bonds. And we do not utilize virtual edges.
Hope this clarifies your questions.

**Comment by Frankie123421** [comment]
Thanks for your prompt reply!
