### ISSUE TITLE
How to select DDPM or Denoised Score-based model?

### ISSUE THREAD

**Issue by yangzhao1230** [harryjo97/GDSS#8]
First, thanks for your great work~
I noticed you used score-based model in this paper, while many people used DDPM (Diffusion Model). I wonder have you ever considered using DDPM to implement this mthod? And why you finally choosed to use score-based model.

**Comment by harryjo97** [comment]
Hi Zhao, 
thanks for your interest in our work.

Since our work constructs a continuous-time diffusion process for graphs, instead of discrete-step perturbation as used in DDPM, DDPM cannot be used. Our proposed GDSS could be discretized to use DDPM which could be a promising direction.

Moreover, as we have explained in the introduction of our paper, we chose the score-based model since 1) it can overcome the limitation of likelihood-based generative models, 2) it can be designed to be permutation invariant, and 3) it is an exciting direction for the graph generation.

If you have any further questions, I would be happy to answer them!
